//! Palettes and the CSS tokens derived from them.
//!
//! Every visual colour in the app comes from here: the aurora background
//! reads `Scheme` directly, and widgets styled by `style.css` read the
//! `@define-color wc_*` tokens generated by [`css_tokens`].

use gtk::prelude::*;
use gtk::{gdk, gio, glib};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PaletteId {
    Aurora,
    Ember,
    Abyss,
    Orchard,
    Graphite,
    /// Generated from the desktop's accent colour plus its complement.
    System,
    /// Generated from two colours the user picks.
    Custom,
}

impl PaletteId {
    pub const ALL: [PaletteId; 7] = [
        PaletteId::Aurora,
        PaletteId::Ember,
        PaletteId::Abyss,
        PaletteId::Orchard,
        PaletteId::Graphite,
        PaletteId::System,
        PaletteId::Custom,
    ];

    pub fn key(self) -> &'static str {
        match self {
            PaletteId::Aurora => "aurora",
            PaletteId::Ember => "ember",
            PaletteId::Abyss => "abyss",
            PaletteId::Orchard => "orchard",
            PaletteId::Graphite => "graphite",
            PaletteId::System => "system",
            PaletteId::Custom => "custom",
        }
    }

    pub fn from_key(key: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|p| p.key() == key)
    }

    pub fn title(self) -> &'static str {
        match self {
            PaletteId::Aurora => "Aurora",
            PaletteId::Ember => "Ember",
            PaletteId::Abyss => "Abyss",
            PaletteId::Orchard => "Orchard",
            PaletteId::Graphite => "Graphite",
            PaletteId::System => "System",
            PaletteId::Custom => "Freestyle",
        }
    }
}

/// One concrete colour scheme (a palette in light or dark).
#[derive(Clone, Copy, Debug)]
pub struct Scheme {
    pub dark: bool,
    /// Background gradient, top → bottom.
    pub base_top: [f32; 3],
    pub base_bottom: [f32; 3],
    /// Drifting aurora blobs.
    pub blobs: [[f32; 3]; 4],
    pub blob_alpha: f32,
    /// Foreground text.
    pub fg: [f32; 3],
    /// Primary accent (operators, focus, selection).
    pub accent: [f32; 3],
    /// Equals-button / result gradient.
    pub hot_a: [f32; 3],
    pub hot_b: [f32; 3],
    /// Text drawn on the hot gradient.
    pub on_hot: [f32; 3],
    /// Graph equation colours.
    pub series: [[f32; 3]; 6],
}

use appcore::color::{
    TEXT_CONTRAST, UI_CONTRAST, WHITE, from_hsl, gradient_for_text, hex, mix, readable_gradient,
    with_contrast,
};
pub use appcore::color::{complement, parse_hex, to_hex};

pub fn scheme(id: PaletteId, dark: bool) -> Scheme {
    let s = built_in(id, dark);
    match id {
        PaletteId::System | PaletteId::Custom => s,
        _ => readable(s, None),
    }
}

fn built_in(id: PaletteId, dark: bool) -> Scheme {
    match (id, dark) {
        (PaletteId::System, _) => generate(DEFAULT_PRIMARY, complement(DEFAULT_PRIMARY), dark),
        (PaletteId::Custom, _) => generate(DEFAULT_PRIMARY, DEFAULT_SECONDARY, dark),
        (PaletteId::Aurora, true) => Scheme {
            dark,
            base_top: hex(0x0b0820),
            base_bottom: hex(0x150d33),
            blobs: [hex(0x7c4dff), hex(0xff4fb0), hex(0x19d3c5), hex(0x3d6bff)],
            blob_alpha: 0.42,
            fg: hex(0xf6f1ff),
            accent: hex(0xb79bff),
            hot_a: hex(0xff7ad9),
            hot_b: hex(0x8a63ff),
            on_hot: hex(0xffffff),
            series: [
                hex(0x5ef2d6),
                hex(0xff7ad9),
                hex(0xffd36e),
                hex(0x8fb4ff),
                hex(0xb79bff),
                hex(0xff8f6b),
            ],
        },
        (PaletteId::Aurora, false) => Scheme {
            dark,
            base_top: hex(0xfbf8ff),
            base_bottom: hex(0xf1ebff),
            blobs: [hex(0xc6b1ff), hex(0xffbfd9), hex(0x9eeedc), hex(0xb4caff)],
            blob_alpha: 0.62,
            fg: hex(0x1f1640),
            accent: hex(0x6d3fe8),
            hot_a: hex(0xf05bbf),
            hot_b: hex(0x7448f0),
            on_hot: hex(0xffffff),
            series: [
                hex(0x0fa38e),
                hex(0xd6339a),
                hex(0xc98a00),
                hex(0x3b6fe0),
                hex(0x6d3fe8),
                hex(0xe0582e),
            ],
        },
        (PaletteId::Ember, true) => Scheme {
            dark,
            base_top: hex(0x170708),
            base_bottom: hex(0x241016),
            blobs: [hex(0xff6a3d), hex(0xff3d7f), hex(0xffb13d), hex(0xa13dff)],
            blob_alpha: 0.36,
            fg: hex(0xfff3ee),
            accent: hex(0xff9a6e),
            hot_a: hex(0xffc35a),
            hot_b: hex(0xff4f6e),
            on_hot: hex(0x2a0b10),
            series: [
                hex(0xffc35a),
                hex(0xff6a8d),
                hex(0x7ee0ff),
                hex(0xc69bff),
                hex(0xff9a6e),
                hex(0x9cf08a),
            ],
        },
        (PaletteId::Ember, false) => Scheme {
            dark,
            base_top: hex(0xfffaf6),
            base_bottom: hex(0xfff0ea),
            blobs: [hex(0xffcfb3), hex(0xffc0d4), hex(0xffe39e), hex(0xe6c9ff)],
            blob_alpha: 0.65,
            fg: hex(0x3a1416),
            accent: hex(0xd94a26),
            hot_a: hex(0xf7a21b),
            hot_b: hex(0xe6365b),
            on_hot: hex(0xffffff),
            series: [
                hex(0xd97a00),
                hex(0xd6335e),
                hex(0x0f8fb8),
                hex(0x8a4fe0),
                hex(0xd94a26),
                hex(0x2f9e3a),
            ],
        },
        (PaletteId::Abyss, true) => Scheme {
            dark,
            base_top: hex(0x020c16),
            base_bottom: hex(0x06182b),
            blobs: [hex(0x00a6ff), hex(0x00e0b0), hex(0x3d4dff), hex(0x7a3dff)],
            blob_alpha: 0.38,
            fg: hex(0xeaf8ff),
            accent: hex(0x55d6ff),
            hot_a: hex(0x3af0d0),
            hot_b: hex(0x3a7bff),
            on_hot: hex(0x02121f),
            series: [
                hex(0x3af0d0),
                hex(0x7ab8ff),
                hex(0xffd36e),
                hex(0xff7ad9),
                hex(0xb79bff),
                hex(0xa4f07a),
            ],
        },
        (PaletteId::Abyss, false) => Scheme {
            dark,
            base_top: hex(0xf5fbff),
            base_bottom: hex(0xe9f5ff),
            blobs: [hex(0xb3e3ff), hex(0xa9f2e2), hex(0xc4ccff), hex(0xd8c8ff)],
            blob_alpha: 0.66,
            fg: hex(0x0b2236),
            accent: hex(0x0a7fc2),
            hot_a: hex(0x10b9a0),
            hot_b: hex(0x2563eb),
            on_hot: hex(0xffffff),
            series: [
                hex(0x0a9e86),
                hex(0x2563eb),
                hex(0xc98a00),
                hex(0xd6339a),
                hex(0x6d3fe8),
                hex(0x3f8f1f),
            ],
        },
        (PaletteId::Orchard, true) => Scheme {
            dark,
            base_top: hex(0x07100a),
            base_bottom: hex(0x0e1c12),
            blobs: [hex(0x4fd16a), hex(0xc6e53f), hex(0x22b3a0), hex(0xffc94a)],
            blob_alpha: 0.32,
            fg: hex(0xf1fbec),
            accent: hex(0x9be37a),
            hot_a: hex(0xe8f05a),
            hot_b: hex(0x35c98a),
            on_hot: hex(0x0b1a0e),
            series: [
                hex(0xe8f05a),
                hex(0x5ee0c0),
                hex(0xff9a6e),
                hex(0x8fb4ff),
                hex(0xff7ad9),
                hex(0x9be37a),
            ],
        },
        (PaletteId::Orchard, false) => Scheme {
            dark,
            base_top: hex(0xf9fdf4),
            base_bottom: hex(0xeef8e6),
            blobs: [hex(0xc2efb8), hex(0xe6f3a6), hex(0xa8eadf), hex(0xffe3a6)],
            blob_alpha: 0.66,
            fg: hex(0x142a12),
            accent: hex(0x2f8f2a),
            hot_a: hex(0xb7c71a),
            hot_b: hex(0x1d9f6a),
            on_hot: hex(0xffffff),
            series: [
                hex(0x2f8f2a),
                hex(0x0f8f80),
                hex(0xd2691e),
                hex(0x3b6fe0),
                hex(0xc0338f),
                hex(0x8a6d00),
            ],
        },
        (PaletteId::Graphite, true) => Scheme {
            dark,
            base_top: hex(0x0c0d10),
            base_bottom: hex(0x15171c),
            blobs: [hex(0x5b6474), hex(0x8b93a3), hex(0x3c4250), hex(0xc9ced8)],
            blob_alpha: 0.20,
            fg: hex(0xf2f3f5),
            accent: hex(0xdfe3ea),
            hot_a: hex(0xf2f3f5),
            hot_b: hex(0xaab1bf),
            on_hot: hex(0x111318),
            series: [
                hex(0xf2f3f5),
                hex(0x9fb7ff),
                hex(0xffc58a),
                hex(0x8ae0c8),
                hex(0xff9ac6),
                hex(0xd5ff8a),
            ],
        },
        (PaletteId::Graphite, false) => Scheme {
            dark,
            base_top: hex(0xfafafa),
            base_bottom: hex(0xeff0f2),
            blobs: [hex(0xd9dce2), hex(0xc8ccd4), hex(0xe7e9ee), hex(0xbfc4cd)],
            blob_alpha: 0.6,
            fg: hex(0x16181d),
            accent: hex(0x2c313a),
            hot_a: hex(0x2c313a),
            hot_b: hex(0x4a515e),
            on_hot: hex(0xffffff),
            series: [
                hex(0x2c313a),
                hex(0x2563eb),
                hex(0xd2691e),
                hex(0x0f8f80),
                hex(0xc0338f),
                hex(0x6b8e00),
            ],
        },
    }
}

// ---------------------------------------------------------------------------
// Generated palettes (System, Freestyle)
// ---------------------------------------------------------------------------

pub const DEFAULT_PRIMARY: [f32; 3] = hex(0x7c4dff);
pub const DEFAULT_SECONDARY: [f32; 3] = hex(0xff6fb5);

/// A complete scheme from two colours: tinted base, an aurora of the two
/// hues and their neighbours, readable text and accent, a hot gradient
/// running secondary → primary, and six well-spread graph colours.
pub fn generate(primary: [f32; 3], secondary: [f32; 3], dark: bool) -> Scheme {
    use appcore::color::to_hsl;
    let (ph, ps, _) = to_hsl(primary);
    let (qh, qs, _) = to_hsl(secondary);
    // Keep greys grey, but give real colours some life.
    let vivid = |s: f32| if s < 0.08 { s } else { s.clamp(0.55, 1.0) };
    let (pv, qv) = (vivid(ps), vivid(qs));
    let series_hues = [
        ph,
        ph + 180.0,
        ph + 60.0,
        ph + 240.0,
        ph + 120.0,
        ph + 300.0,
    ];
    let (hot_a, hot_b);
    let scheme = if dark {
        hot_a = from_hsl(qh, qv, 0.66);
        hot_b = from_hsl(ph, pv, 0.60);
        Scheme {
            dark,
            base_top: from_hsl(ph, (ps * 0.7).min(0.55), 0.055),
            base_bottom: from_hsl(ph, (ps * 0.75).min(0.6), 0.105),
            blobs: [
                from_hsl(ph, pv, 0.58),
                from_hsl(qh, qv, 0.60),
                from_hsl(ph + 35.0, pv, 0.55),
                from_hsl(qh - 35.0, qv, 0.58),
            ],
            blob_alpha: 0.40,
            fg: from_hsl(ph, ps.min(0.5), 0.965),
            accent: from_hsl(ph, pv, 0.76),
            hot_a,
            hot_b,
            on_hot: [1.0, 1.0, 1.0],
            series: series_hues.map(|h| from_hsl(h, 0.8, 0.66)),
        }
    } else {
        hot_a = from_hsl(qh, qv.min(0.8), 0.58);
        hot_b = from_hsl(ph, pv.min(0.75), 0.50);
        Scheme {
            dark,
            base_top: from_hsl(ph, ps.min(0.6), 0.985),
            base_bottom: from_hsl(ph, ps.min(0.55), 0.955),
            blobs: [
                from_hsl(ph, pv.min(0.8), 0.83),
                from_hsl(qh, qv.min(0.8), 0.84),
                from_hsl(ph + 35.0, pv.min(0.8), 0.85),
                from_hsl(qh - 35.0, qv.min(0.8), 0.83),
            ],
            blob_alpha: 0.62,
            fg: from_hsl(ph, ps.min(0.45), 0.15),
            accent: from_hsl(ph, pv.min(0.9), 0.42),
            hot_a,
            hot_b,
            on_hot: [1.0, 1.0, 1.0],
            series: series_hues.map(|h| from_hsl(h, 0.7, 0.42)),
        }
    };
    readable(scheme, Some(from_hsl(ph, 0.4, 0.10)))
}

/// Keep what's drawn on top legible: the equals glyph against its whole
/// gradient (a large glyph: 3:1), accent text against the background
/// (4.5:1) and graph lines against it (3:1). Generated palettes can come
/// from anything (a neon-yellow desktop accent, pure grey…) and also pick
/// light or `dark_text` for the glyph; built-ins keep their glyph colour and
/// only have their colours nudged.
fn readable(s: Scheme, dark_text: Option<[f32; 3]>) -> Scheme {
    let fix =
        |c, target| with_contrast(with_contrast(c, s.base_top, target), s.base_bottom, target);
    let (on_hot, hot_a, hot_b) = match dark_text {
        Some(dark) => readable_gradient(s.hot_a, s.hot_b, WHITE, dark, UI_CONTRAST),
        None => {
            let (a, b) = gradient_for_text(s.on_hot, s.hot_a, s.hot_b, UI_CONTRAST);
            (s.on_hot, a, b)
        }
    };
    Scheme {
        on_hot,
        hot_a,
        hot_b,
        accent: fix(s.accent, TEXT_CONTRAST),
        series: s.series.map(|c| fix(c, UI_CONTRAST)),
        ..s
    }
}

pub fn rgba(c: [f32; 3], a: f32) -> gdk::RGBA {
    gdk::RGBA::new(c[0], c[1], c[2], a)
}

fn css_rgb(c: [f32; 3]) -> String {
    format!(
        "rgb({},{},{})",
        (c[0] * 255.0).round() as u8,
        (c[1] * 255.0).round() as u8,
        (c[2] * 255.0).round() as u8
    )
}

/// Our tokens and every libadwaita surface colour, derived from a scheme.
///
/// The app defines *all* libadwaita colours (legacy `@define-color` names and
/// the CSS variables) so it looks the same everywhere, including when a
/// desktop shell drops its own palette into `~/.config/gtk-4.0/gtk.css`.
pub fn css_tokens(s: &Scheme) -> String {
    let white = [1.0, 1.0, 1.0];
    let black = [0.0, 0.0, 0.0];
    let fg = css_rgb(s.fg);
    let (glass, glass_hi, glass_border, shade, num) = if s.dark {
        (
            "alpha(white, 0.055)",
            "alpha(white, 0.11)",
            "alpha(white, 0.10)",
            "alpha(black, 0.32)",
            "alpha(white, 0.085)",
        )
    } else {
        (
            "alpha(white, 0.50)",
            "alpha(white, 0.78)",
            "alpha(white, 0.85)",
            "alpha(#3a2a6a, 0.10)",
            "alpha(white, 0.72)",
        )
    };
    // Surfaces.
    let (window, view, dialog, popover, card, sidebar) = if s.dark {
        let base = s.base_bottom;
        (
            css_rgb(base),
            css_rgb(mix(base, black, 0.15)),
            css_rgb(mix(mix(base, s.accent, 0.06), white, 0.05)),
            css_rgb(mix(mix(base, s.accent, 0.08), white, 0.07)),
            "alpha(white, 0.07)".to_string(),
            css_rgb(mix(base, white, 0.03)),
        )
    } else {
        let base = s.base_top;
        (
            css_rgb(base),
            css_rgb(mix(base, white, 0.6)),
            css_rgb(mix(base, white, 0.7)),
            css_rgb(mix(base, white, 0.8)),
            "alpha(white, 0.75)".to_string(),
            css_rgb(mix(base, s.accent, 0.04)),
        )
    };
    let accent = css_rgb(s.accent);
    let on_accent = if s.dark { "rgb(20,12,40)" } else { "white" };
    let mut out = format!(
        r#"
@define-color wc_fg {fg};
@define-color wc_fg_dim alpha({fg}, 0.62);
@define-color wc_fg_faint alpha({fg}, 0.38);
@define-color wc_glass {glass};
@define-color wc_glass_hi {glass_hi};
@define-color wc_glass_border {glass_border};
@define-color wc_glass_num {num};
@define-color wc_shade {shade};
@define-color wc_accent {accent};
@define-color wc_hot_a {hot_a};
@define-color wc_hot_b {hot_b};
@define-color wc_on_hot {on_hot};
@define-color wc_base {base};
"#,
        hot_a = css_rgb(s.hot_a),
        hot_b = css_rgb(s.hot_b),
        on_hot = css_rgb(s.on_hot),
        base = css_rgb(s.base_bottom),
    );
    let pairs: [(&str, String, String); 9] = [
        ("window", window.clone(), fg.clone()),
        ("view", view, fg.clone()),
        ("headerbar", window.clone(), fg.clone()),
        ("sidebar", sidebar.clone(), fg.clone()),
        ("secondary_sidebar", sidebar, fg.clone()),
        ("dialog", dialog, fg.clone()),
        ("popover", popover, fg.clone()),
        ("card", card, fg.clone()),
        ("overview", window, fg.clone()),
    ];
    let mut vars = String::new();
    for (name, bg, fgc) in &pairs {
        out.push_str(&format!(
            "@define-color {name}_bg_color {bg};\n@define-color {name}_fg_color {fgc};\n"
        ));
        let dash = name.replace('_', "-");
        vars.push_str(&format!(
            "  --{dash}-bg-color: {bg};\n  --{dash}-fg-color: {fgc};\n"
        ));
    }
    out.push_str(&format!(
        "@define-color accent_color {accent};\n@define-color accent_bg_color {accent};\n@define-color accent_fg_color {on_accent};\n\
         @define-color headerbar_backdrop_color @window_bg_color;\n\
         :root {{\n{vars}  --accent-bg-color: {accent};\n  --accent-color: {accent};\n  --accent-fg-color: {on_accent};\n  \
         --headerbar-backdrop-color: var(--window-bg-color);\n}}\n"
    ));
    out
}

// ---------------------------------------------------------------------------
// Hub: one place that knows the active scheme and tells subscribers.
// ---------------------------------------------------------------------------

use std::cell::{Cell, RefCell};
use std::rc::Rc;

/// Returns false once it should be dropped (its widget is gone).
type Subscriber = Box<dyn Fn(&Scheme) -> bool>;

pub struct Hub {
    palette: Cell<PaletteId>,
    /// Freestyle: (primary, secondary).
    custom: Cell<([f32; 3], [f32; 3])>,
    /// Cached desktop accent (read lazily, kept fresh by a portal watch).
    system_accent: Cell<Option<[f32; 3]>>,
    portal_watch: RefCell<Option<gio::SignalSubscription>>,
    provider: gtk::CssProvider,
    subscribers: RefCell<Vec<Subscriber>>,
}

impl Hub {
    pub fn new(palette: PaletteId, custom: ([f32; 3], [f32; 3])) -> Rc<Self> {
        let provider = gtk::CssProvider::new();
        provider.connect_parsing_error(|_, section, err| {
            eprintln!("css error at {}: {err}", section.to_str());
        });
        gtk::style_context_add_provider_for_display(
            &gdk::Display::default().expect("display"),
            &provider,
            // Above USER: shells like Noctalia/matugen write ~/.config/gtk-4.0/gtk.css.
            gtk::STYLE_PROVIDER_PRIORITY_USER + 2,
        );
        let hub = Rc::new(Hub {
            palette: Cell::new(palette),
            custom: Cell::new(custom),
            system_accent: Cell::new(None),
            portal_watch: RefCell::new(None),
            provider,
            subscribers: RefCell::default(),
        });
        let sm = adw::StyleManager::default();
        let weak = Rc::downgrade(&hub);
        sm.connect_dark_notify(move |_| {
            if let Some(hub) = weak.upgrade() {
                hub.apply();
            }
        });
        let weak = Rc::downgrade(&hub);
        sm.connect_accent_color_rgba_notify(move |_| {
            if let Some(hub) = weak.upgrade() {
                hub.refresh_system_accent();
            }
        });
        hub.apply();
        hub
    }

    /// The scheme for any palette in light or dark (settings previews).
    pub fn scheme_for(&self, id: PaletteId, dark: bool) -> Scheme {
        match id {
            PaletteId::System => {
                let p = self.system_accent();
                generate(p, complement(p), dark)
            }
            PaletteId::Custom => {
                let (p, q) = self.custom.get();
                generate(p, q, dark)
            }
            _ => scheme(id, dark),
        }
    }

    pub fn scheme(&self) -> Scheme {
        self.scheme_for(self.palette.get(), adw::StyleManager::default().is_dark())
    }

    pub fn palette(&self) -> PaletteId {
        self.palette.get()
    }

    pub fn set_palette(&self, palette: PaletteId) {
        self.palette.set(palette);
        self.apply();
    }

    pub fn custom(&self) -> ([f32; 3], [f32; 3]) {
        self.custom.get()
    }

    pub fn set_custom(&self, primary: [f32; 3], secondary: [f32; 3]) {
        self.custom.set((primary, secondary));
        if self.palette.get() == PaletteId::Custom {
            self.apply();
        }
    }

    /// The desktop's accent colour: the exact value from the Settings
    /// portal (what shells like Noctalia set), else libadwaita's accent.
    pub fn system_accent(&self) -> [f32; 3] {
        if let Some(c) = self.system_accent.get() {
            return c;
        }
        let c = read_portal_accent().unwrap_or_else(|| {
            let a = adw::StyleManager::default().accent_color_rgba();
            [a.red(), a.green(), a.blue()]
        });
        self.system_accent.set(Some(c));
        self.watch_portal();
        c
    }

    fn refresh_system_accent(&self) {
        self.system_accent.set(None);
        if self.palette.get() == PaletteId::System {
            self.apply();
        }
    }

    /// Live-follow accent changes (e.g. Noctalia re-theming from a wallpaper).
    fn watch_portal(&self) {
        if self.portal_watch.borrow().is_some() {
            return;
        }
        let Ok(conn) = gio::bus_get_sync(gio::BusType::Session, gio::Cancellable::NONE) else {
            return;
        };
        // The callback can't hold the hub, so it nudges libadwaita's
        // accent-notify path through a main-context idle instead.
        let sub = conn.subscribe_to_signal(
            Some("org.freedesktop.portal.Desktop"),
            Some("org.freedesktop.portal.Settings"),
            Some("SettingChanged"),
            Some("/org/freedesktop/portal/desktop"),
            Some("org.freedesktop.appearance"),
            gio::DBusSignalFlags::NONE,
            |signal| {
                let key = signal.parameters.child_value(1);
                if key.str() == Some("accent-color") {
                    PORTAL_ACCENT_CHANGED.with(|f| {
                        if let Some(f) = f.borrow().as_ref() {
                            f();
                        }
                    });
                }
            },
        );
        self.portal_watch.replace(Some(sub));
    }

    /// Call `f` now and whenever the scheme changes.
    pub fn subscribe(&self, f: impl Fn(&Scheme) + 'static) {
        f(&self.scheme());
        self.subscribers.borrow_mut().push(Box::new(move |s| {
            f(s);
            true
        }));
    }

    /// Like [`Hub::subscribe`], but only while `widget` is alive.
    pub fn subscribe_while<W: IsA<glib::Object>>(
        &self,
        widget: &W,
        f: impl Fn(&W, &Scheme) + 'static,
    ) {
        f(widget, &self.scheme());
        let weak = widget.downgrade();
        self.subscribers
            .borrow_mut()
            .push(Box::new(move |s| match weak.upgrade() {
                Some(w) => {
                    f(&w, s);
                    true
                }
                None => false,
            }));
    }

    fn apply(&self) {
        let s = self.scheme();
        self.provider.load_from_string(&css_tokens(&s));
        // Collect first: a subscriber may itself subscribe or open UI.
        let subs: Vec<Subscriber> = std::mem::take(&mut *self.subscribers.borrow_mut());
        let mut keep: Vec<Subscriber> = subs.into_iter().filter(|f| f(&s)).collect();
        keep.append(&mut self.subscribers.borrow_mut());
        *self.subscribers.borrow_mut() = keep;
    }
}

thread_local! {
    static PORTAL_ACCENT_CHANGED: RefCell<Option<Box<dyn Fn()>>> = const { RefCell::new(None) };
}

/// Route portal accent changes to `hub` (main thread only).
pub fn follow_portal_accent(hub: &Rc<Hub>) {
    let weak = Rc::downgrade(hub);
    PORTAL_ACCENT_CHANGED.with(|f| {
        f.replace(Some(Box::new(move || {
            if let Some(hub) = weak.upgrade() {
                hub.refresh_system_accent();
            }
        })));
    });
}

/// `org.freedesktop.appearance accent-color` from the Settings portal:
/// `(ddd)` in 0..1, or out of range when the desktop has none set.
fn read_portal_accent() -> Option<[f32; 3]> {
    let conn = gio::bus_get_sync(gio::BusType::Session, gio::Cancellable::NONE).ok()?;
    let reply = conn
        .call_sync(
            Some("org.freedesktop.portal.Desktop"),
            "/org/freedesktop/portal/desktop",
            "org.freedesktop.portal.Settings",
            "ReadOne",
            Some(&("org.freedesktop.appearance", "accent-color").to_variant()),
            Some(glib::VariantTy::new("(v)").expect("valid type")),
            gio::DBusCallFlags::NONE,
            500,
            gio::Cancellable::NONE,
        )
        .ok()?;
    let inner = reply.child_value(0).as_variant()?;
    let (r, g, b) = inner.get::<(f64, f64, f64)>()?;
    let ok = |v: f64| (0.0..=1.0).contains(&v);
    (ok(r) && ok(g) && ok(b)).then_some([r as f32, g as f32, b as f32])
}

#[cfg(test)]
mod tests {
    use super::*;
    use appcore::color::{contrast, worst_contrast};

    fn check(s: &Scheme, what: &str) -> Vec<String> {
        let mut bad = Vec::new();
        let hot = worst_contrast(s.on_hot, &[s.hot_a, s.hot_b, mix(s.hot_a, s.hot_b, 0.5)]);
        if hot < UI_CONTRAST {
            bad.push(format!("{what}: equals glyph {hot:.2}"));
        }
        let accent = worst_contrast(s.accent, &[s.base_top, s.base_bottom]);
        if accent < TEXT_CONTRAST {
            bad.push(format!("{what}: accent {accent:.2}"));
        }
        for (i, c) in s.series.iter().enumerate() {
            let k = worst_contrast(*c, &[s.base_top, s.base_bottom]);
            if k < UI_CONTRAST {
                bad.push(format!("{what}: series {i} {k:.2}"));
            }
        }
        let fg = contrast(s.fg, s.base_bottom).min(contrast(s.fg, s.base_top));
        if fg < TEXT_CONTRAST {
            bad.push(format!("{what}: fg {fg:.2}"));
        }
        bad
    }

    #[test]
    fn generated_palettes_stay_readable_for_extreme_colours() {
        let inputs = [
            ("white", WHITE),
            ("black", [0.0, 0.0, 0.0]),
            ("grey", hex(0x808080)),
            ("yellow", hex(0xffff00)),
            ("blue", hex(0x0000ff)),
            ("lime", hex(0x00ff00)),
            ("violet", hex(0x7c4dff)),
        ];
        let mut bad = Vec::new();
        for (name, c) in inputs {
            for dark in [false, true] {
                bad.extend(check(
                    &generate(c, complement(c), dark),
                    &format!("system {name} {dark}"),
                ));
                bad.extend(check(
                    &generate(c, c, dark),
                    &format!("freestyle {name} {dark}"),
                ));
            }
        }
        assert!(bad.is_empty(), "{bad:#?}");
    }

    #[test]
    fn built_in_palettes_stay_readable() {
        let mut bad = Vec::new();
        for id in PaletteId::ALL {
            for dark in [false, true] {
                bad.extend(check(&scheme(id, dark), &format!("{id:?} {dark}")));
            }
        }
        assert!(bad.is_empty(), "{bad:#?}");
    }
}
