// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

//! `NumbersAndOperatorsEnum` — every button the calculator UI can press.
//! Discriminants are identical to upstream (most map 1:1 onto engine
//! `Command` ids), so keep them in sync with
//! `Calculator.ViewModels/Common/NumbersAndOperatorsEnum.cs`.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum Button {
    None = 0,
    Zero = 130,
    One = 131,
    Two = 132,
    Three = 133,
    Four = 134,
    Five = 135,
    Six = 136,
    Seven = 137,
    Eight = 138,
    Nine = 139,
    Add = 93,
    Subtract = 94,
    Multiply = 92,
    Divide = 91,
    Invert = 114,
    Equals = 121,
    Decimal = 84,
    Sqrt = 110,
    Percent = 118,
    Negate = 80,
    Backspace = 83,
    ClearEntry = 82,
    Clear = 81,
    Degree = 321,
    Radians = 322,
    Grads = 323,
    Degrees = 324,
    OpenParenthesis = 128,
    CloseParenthesis = 129,
    Pi = 120,
    Sin = 102,
    Cos = 103,
    Tan = 104,
    Factorial = 113,
    XPower2 = 111,
    Mod = 95,
    FToE = 119,
    LogBaseE = 108,
    InvSin = 202,
    InvCos = 203,
    InvTan = 204,
    LogBase10 = 109,
    XPowerY = 97,
    YRootX = 96,
    TenPowerX = 117,
    EPowerX = 205,
    Exp = 127,
    IsScientificMode = 201,
    IsStandardMode = 200,
    IsProgrammerMode = 209,
    DecButton = 314,
    OctButton = 315,
    HexButton = 313,
    BinButton = 316,
    And = 86,
    Ror = 100,
    Rol = 99,
    Or = 87,
    Lsh = 89,
    Rsh = 90,
    Xor = 88,
    Not = 101,
    A = 140,
    B = 141,
    C = 142,
    D = 143,
    E = 144,
    F = 145,
    /// No direct mapping to CalcEngine.
    Memory = 146,
    Sinh = 105,
    Cosh = 106,
    Tanh = 107,
    InvSinh = 206,
    InvCosh = 207,
    InvTanh = 208,
    Qword = 317,
    Dword = 318,
    Word = 319,
    Byte = 320,
    Cube = 112,
    DMS = 115,
    Hyp = 325,
    Sec = 400,
    Csc = 402,
    Cot = 404,
    InvSec = 401,
    InvCsc = 403,
    InvCot = 405,
    Sech = 406,
    Csch = 408,
    Coth = 410,
    InvSech = 407,
    InvCsch = 409,
    InvCoth = 411,
    CubeRoot = 116,
    TwoPowerX = 412,
    LogBaseY = 500,
    Nand = 501,
    Nor = 502,
    Abs = 413,
    Floor = 414,
    Ceil = 415,
    Rand = 600,
    Euler = 601,
    RshL = 505,
    RolC = 416,
    RorC = 417,
    MemoryAdd = 125,
    MemorySubtract = 126,
    MemoryRecall = 123,
    MemoryClear = 122,
    BitflipButton = 1000,
    FullKeypadButton = 1001,
    LessThan = 1002,
    LessThanOrEqualTo = 1003,
    GreaterThan = 1004,
    GreaterThanOrEqualTo = 1005,
    X = 1006,
    Y = 1007,
    Submit = 1008,
}

/// `BINSTART`/`BINPOS0..BINPOS63`/`BINEND`: bit-flip buttons are `700 + bit`.
pub const BIN_START: u32 = 700;
pub const BIN_END: u32 = 763;

impl Button {
    pub fn id(self) -> u32 {
        self as u32
    }

    /// Every button, for id → enum lookups.
    pub const ALL: [Button; 121] = [
        Button::None,
        Button::Zero,
        Button::One,
        Button::Two,
        Button::Three,
        Button::Four,
        Button::Five,
        Button::Six,
        Button::Seven,
        Button::Eight,
        Button::Nine,
        Button::Add,
        Button::Subtract,
        Button::Multiply,
        Button::Divide,
        Button::Invert,
        Button::Equals,
        Button::Decimal,
        Button::Sqrt,
        Button::Percent,
        Button::Negate,
        Button::Backspace,
        Button::ClearEntry,
        Button::Clear,
        Button::Degree,
        Button::Radians,
        Button::Grads,
        Button::Degrees,
        Button::OpenParenthesis,
        Button::CloseParenthesis,
        Button::Pi,
        Button::Sin,
        Button::Cos,
        Button::Tan,
        Button::Factorial,
        Button::XPower2,
        Button::Mod,
        Button::FToE,
        Button::LogBaseE,
        Button::InvSin,
        Button::InvCos,
        Button::InvTan,
        Button::LogBase10,
        Button::XPowerY,
        Button::YRootX,
        Button::TenPowerX,
        Button::EPowerX,
        Button::Exp,
        Button::IsScientificMode,
        Button::IsStandardMode,
        Button::IsProgrammerMode,
        Button::DecButton,
        Button::OctButton,
        Button::HexButton,
        Button::BinButton,
        Button::And,
        Button::Ror,
        Button::Rol,
        Button::Or,
        Button::Lsh,
        Button::Rsh,
        Button::Xor,
        Button::Not,
        Button::A,
        Button::B,
        Button::C,
        Button::D,
        Button::E,
        Button::F,
        Button::Memory,
        Button::Sinh,
        Button::Cosh,
        Button::Tanh,
        Button::InvSinh,
        Button::InvCosh,
        Button::InvTanh,
        Button::Qword,
        Button::Dword,
        Button::Word,
        Button::Byte,
        Button::Cube,
        Button::DMS,
        Button::Hyp,
        Button::Sec,
        Button::Csc,
        Button::Cot,
        Button::InvSec,
        Button::InvCsc,
        Button::InvCot,
        Button::Sech,
        Button::Csch,
        Button::Coth,
        Button::InvSech,
        Button::InvCsch,
        Button::InvCoth,
        Button::CubeRoot,
        Button::TwoPowerX,
        Button::LogBaseY,
        Button::Nand,
        Button::Nor,
        Button::Abs,
        Button::Floor,
        Button::Ceil,
        Button::Rand,
        Button::Euler,
        Button::RshL,
        Button::RolC,
        Button::RorC,
        Button::MemoryAdd,
        Button::MemorySubtract,
        Button::MemoryRecall,
        Button::MemoryClear,
        Button::BitflipButton,
        Button::FullKeypadButton,
        Button::LessThan,
        Button::LessThanOrEqualTo,
        Button::GreaterThan,
        Button::GreaterThanOrEqualTo,
        Button::X,
        Button::Y,
        Button::Submit,
    ];

    /// Inverse of [`Button::id`].
    pub fn from_id(id: u32) -> Option<Button> {
        Self::ALL.iter().copied().find(|b| b.id() == id)
    }

    /// Digit buttons 0–F in order.
    pub const DIGITS: [Button; 16] = [
        Button::Zero,
        Button::One,
        Button::Two,
        Button::Three,
        Button::Four,
        Button::Five,
        Button::Six,
        Button::Seven,
        Button::Eight,
        Button::Nine,
        Button::A,
        Button::B,
        Button::C,
        Button::D,
        Button::E,
        Button::F,
    ];

    /// The digit value for `Zero..=Nine` and `A..=F`.
    pub fn digit_value(self) -> Option<u32> {
        Self::DIGITS
            .iter()
            .position(|&b| b == self)
            .map(|i| i as u32)
    }
}
